spring.application.name=campaign-platform
server.port=8082
spring.jpa.hibernate.ddl-auto=validate
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.datasource.url=jdbc:postgresql://localhost:5432/campaign_platform
spring.datasource.username=postgres
spring.config.import=optional:classpath:application-secrets.properties